# Generated by Django 6.0.7 on 2026-08-05 19:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/applications/', validators=[accounts.models.validate_resume]),
        ),
    ]
