# Generated by Django 6.0.7 on 2026-08-05 21:04

from django.db import migrations


def backfill_history(apps, schema_editor):
    Application = apps.get_model('jobs', 'Application')
    ApplicationStatusHistory = apps.get_model('jobs', 'ApplicationStatusHistory')
    
    # For every application, create a history record matching its current status
    for app in Application.objects.all():
        ApplicationStatusHistory.objects.get_or_create(
            application=app,
            status=app.status,
            defaults={'note': 'Initial status (migrated)'}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_status_applicationstatushistory'),
    ]

    operations = [
        migrations.RunPython(backfill_history, reverse_code=migrations.RunPython.noop),
    ]
