# Generated by Django 6.0.7 on 2026-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_company_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiternote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Technical Round', 'Technical Round'), ('HR Round', 'HR Round'), ('Offer Extended', 'Offer Extended'), ('Hired', 'Hired'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Technical Round', 'Technical Round'), ('HR Round', 'HR Round'), ('Offer Extended', 'Offer Extended'), ('Hired', 'Hired'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], max_length=30),
        ),
    ]
