# Generated by Django 6.0.7 on 2026-08-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_recruiternote_updated_at_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiternote',
            name='rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
