# Generated by Django 6.0.7 on 2026-08-06 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_about_profile_certifications_and_more'),
        ('jobs', '0009_recruiternote_updated_at_alter_application_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_filename', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resume_score', models.IntegerField(default=0)),
                ('ats_score', models.IntegerField(default=0)),
                ('summary_review', models.TextField()),
                ('skills_detected', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('grammar_suggestions', models.JSONField(default=list)),
                ('formatting_suggestions', models.JSONField(default=list)),
                ('actionable_improvements', models.JSONField(default=list)),
                ('match_percentage', models.IntegerField(blank=True, null=True)),
                ('matching_skills', models.JSONField(blank=True, default=list)),
                ('job_missing_skills', models.JSONField(blank=True, default=list)),
                ('job_recommendations', models.JSONField(blank=True, default=list)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_analyses', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
